### ISSUE TITLE
Build broken with go 1.18 

### ISSUE THREAD

**Issue by jameshcorbett** [NearNodeFlash/nnf-sos#17]
With go 1.18, the `make controller-gen` target fails to create a `bin/` directory and to create `bin/controller-gen`. All of the targets that depend on make controller-gen (e.g. `make docker-build`) therefore fail as well.

See also https://github.com/HewlettPackard/dws/issues/14

**Comment by roehrich-hpe** [comment]
Resolved in PR 57.
