### ISSUE TITLE
Persistentdw must claim ownership on its instance and release when finished

### ISSUE THREAD

**Issue by ajfloeder** [NearNodeFlash/nnf-sos#60]
Right now there is nothing in the code protecting a persistent storage instance from deletion from a workflow containing `#DW destroy_persistent myPSI` when 1 or more other workflows are using that persistent storage instance with `#DW persistentdw myPSI`.
1. workflows containing `#DW persistentdw myPSI` directives must add a label to `myPSI` when they use it
1. workflows containing `#DW persistentdw myPSI` directives must remove that label from `myPSI` when they reach the `teardown` state
1. the workflow containing `#DW destroy_persistent myPSI` directive must wait until all workflows submitted prior to itself have finished with `myPSI` (removed their labels) before deleting `myPSI`.
1. any workflow containing `#DW persistentdw myPSI` submitting after `myPSI's` status.state=deleting fails in the same way that it would when `myPSI` doesn't exist.

**Comment by NateRoiger** [comment]
Would this be better handled by a finalizer? Each user of the workflow could add its own finalizer - the NamespacedName() comes to mind.

**Comment by ajfloeder** [comment]
@NateRoiger - yes I think so. In fact it seems this case is exactly what finalizers do.

**Comment by ajfloeder** [comment]
@matthew-richerson Fixed this issue in this commit:

020f28dab62d8aff2350adb1abd53241a48e5809
